services:
  - type: web
    name: web-app-assignment
    runtime: python
    plan: free
    buildCommand: "python -m pip install poetry && python -m poetry install"
    startCommand: "python -m poetry run gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name-here
          property: connectionString